name: Build 

# IOTEMBSYS10: Change this to only apply to specific branches, if desired
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      # IOTEMBSYS10: Add a step to checkout the repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: firmware-workspace
      # IOTEMBSYS10: Add a step to initialize the west workspace
      - name: Initialize
        working-directory: firmware-workspace
        run: |
          west init -l .
          west update

      # IOTEMBSYS10: Add a step to build the application
      - name: Build firmware
        working-directory: firmware-workspace
        run: |
        west build -p -b stm32l496_cell app -- -DEXTRA_CONF_FILE="mcumgr.conf" -DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE=\"firmware_space/conf/root-rsa-2048.pem\"